#!/bin/bash

cd aviation_data_huiyi
echo ================================= NTSB Cleaning ================================
./run_all
print "================================= NTSB Cleaning ================================\n\n"


cd ../faa
echo ================================= FAA Cleaning =================================
python clean_data.py
print "================================= FAA Cleaning =================================\n\n" 

cd ../

echo ====================== Join FAA/NTSB Data ======================================
python join_faa_ntsb.py
print "====================== Join FAA/NTSB Data ======================================\n\n"

echo ==================== Combine FAA/NTSB Data with Volume Data ====================
python flight_vol.py
print "==================== Combine FAA/NTSB Data with Volume Data ====================\n\n"

echo ====================== Combine Abrev w/Volume + Incident Data ==================
python combine.py
print "====================== Combine Abrev w/Volume + Incident Data ==================\n\n"
