#!/bin/bash
test_var=false
if [ -z "$1" ]; then
    test_var=false
else
    if [ $1 = '-t' ] ; then
        test_var=true
    fi
fi

cd faa_ntsb_analysis
echo ================================= FAA Cleaning ================================
python find_faa_code.py
printf "================================= FAA Cleaning ================================\n\n"

echo ================================= NTSB Cleaning =================================
python find_ntsb_code.py
printf "================================= NTSB Cleaning =================================\n\n" 
cd ../

echo ====================== Join FAA/NTSB Data ======================================
python join_faa_ntsb.py
printf "====================== Join FAA/NTSB Data ======================================\n\n"

cd preprocess_asrs
echo ================================= ASRS Cleaning ================================
python clean.py
printf "================================= ASRS Cleaning ================================\n\n"
cd ../

cp preprocess_asrs/outputs/*.csv asrs_analysis/datasets
cd asrs_analysis
echo ================================= ASRS Analysis ================================
if $test_var; then
    bash -e ./run_all -t
else
    bash -e ./run_all
fi
printf "================================= ASRS Analysis ================================\n\n"
cd ../

echo ====================== Combine Abrev w/Volume + Incident Data ==================
if $test_var; then
    python combine.py -t
else
    python combine.py
fi
printf "====================== Combine Abrev w/Volume + Incident Data ==================\n\n"
