#!/bin/bash

cd faa_ntsb_analysis
echo ================================= NTSB Cleaning ================================
python find_faa_code.py
printf "================================= NTSB Cleaning ================================\n\n"

echo ================================= FAA Cleaning =================================
python find_ntsb_code.py
printf "================================= FAA Cleaning =================================\n\n" 
cd ../

# cd aviation_data_huiyi
# echo ================================= NTSB Cleaning ================================
# ./run_all
# printf "================================= NTSB Cleaning ================================\n\n"
#
#
# cd ../faa
# echo ================================= FAA Cleaning =================================
# python clean_data.py
# printf "================================= FAA Cleaning =================================\n\n" 

echo ====================== Join FAA/NTSB Data ======================================
python join_faa_ntsb.py
printf "====================== Join FAA/NTSB Data ======================================\n\n"

cd preprocess_asrs
echo ================================= ASRS Cleaning ================================
python clean.py
printf "================================= ASRS Cleaning ================================\n\n"
cd ../

cp preprocess_asrs/outputs/*.csv asrs_analysis/datasets
cd asrs_analysis
echo ================================= ASRS Analysis ================================
./run_all
printf "================================= ASRS Analysis ================================\n\n"
cd ../


echo ==================== Combine FAA/NTSB Data with Volume Data ====================
python flight_vol.py
printf "==================== Combine FAA/NTSB Data with Volume Data ====================\n\n"


echo ====================== Combine Abrev w/Volume + Incident Data ==================
python combine.py
printf "====================== Combine Abrev w/Volume + Incident Data ==================\n\n"
