#!/bin/bash
test_var=false
if [ -z "$1" ]; then
    test_var=false
else
    if [ $1 = '-t' ] ; then
        test_var=true
    fi
fi

echo ================ Analyzing Abbreviations ================
if $test_var; then
    python abbrev_words_analysis.py -t -summary_only
else
    python abbrev_words_analysis.py -summary_only
fi
if $test_var; then
    python abbrev_words_analysis.py -t
else
    python abbrev_words_analysis.py
fi
printf "========== Finished Analyzing Abbreviations =============\n\n"

echo ============= Creating Abbreviations Counts =============
if $test_var; then
    python top_down.py -t
else
    python top_down.py
fi
printf "============= Finished Abbreviations Counts =============\n\n"

echo ==================== Analyzing LIWC ====================
python liwc_analysis.py
printf "=============== Finished Analyzing LIWC ================\n\n"

echo ================== Analyzing Doc2Vec ==================
if $test_var; then
    python cos_sim.py -t
else
    python cos_sim.py
fi
printf "=============== Finished Analyzing Doc2Vec ============\n\n"
