#!/bin/bash
test_var=false
if [ -z "$1" ]; then
    test_var=false
else
    if [ $1 = '-t' ] ; then
        test_var=true
    fi
fi

echo ================ Analyzing Abbreviations ================
if $test_var; then
    python abbrev_words_analysis.py -t
else
    python abbrev_words_analysis.py
fi
printf "========== Finished Analyzing Abbreviations =============\n\n"

echo ============= Creating Abbreviations Counts =============
python top_down.py
printf "============= Finished Abbreviations Counts =============\n\n"

echo ==================== Analyzing LIWC ====================
python liwc_analysis.py
printf "=============== Finished Analyzing LIWC ================\n\n"

echo ================== Analyzing Doc2Vec ==================
# python cos_sim.py
if $test_var; then
    python cos_sim.py -t
else
    python cos_sim.py
fi
printf "=============== Finished Analyzing Doc2Vec ============\n\n"
