#!/bin/bash
echo ================ Analyzing Abbreviations ================
python abbrev_words_analysis.py
printf "========== Finished Analyzing Abbreviations =============\n\n"

echo ============= Creating Abbreviations Counts =============
python top_down.py
printf "============= Finished Abbreviations Counts =============\n\n"

echo ==================== Analyzing LIWC ====================
python liwc_analysis.py
printf "=============== Finished Analyzing LIWC ================\n\n"

echo ================== Analyzing Doc2Vec ==================
python cos_sim.py
printf "=============== Finished Analyzing Doc2Vec ============\n\n"
